config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end  
# match "people_settings/:action" => "people_settings"

app/models/person.rb
class Person < User
  unloadable
  self.inheritance_column = :_type_disabled

  belongs_to :department

  include Redmine::SafeAttributes

  GENDERS = [[l(:label_people_male), 0], [l(:label_people_female), 1]]

  scope :in_department, lambda {|department|
    department_id = department.is_a?(Department) ? department.id : department.to_i
    { :conditions => {:department_id => department_id, :type => "User"} }
  }
  scope :not_in_department, lambda {|department|
    department_id = department.is_a?(Department) ? department.id : department.to_i
    { :conditions => ["(#{User.table_name}.department_id != ?) OR (#{User.table_name}.department_id IS NULL)", department_id] }
  }  

  scope :seach_by_name, lambda {|search| {:conditions =>   ["(LOWER(#{Person.table_name}.firstname) LIKE ? OR 
                                                                    LOWER(#{Person.table_name}.lastname) LIKE ? OR 
                                                                    LOWER(#{Person.table_name}.middlename) LIKE ? OR 
                                                                    LOWER(#{Person.table_name}.login) LIKE ? OR 
                                                                    LOWER(#{Person.table_name}.mail) LIKE ?)", 
                                                                  search.downcase + "%",
                                                                  search.downcase + "%",
                                                                  search.downcase + "%",
                                                                  search.downcase + "%",
                                                                  search.downcase + "%"] }}

  validates_uniqueness_of :firstname, :scope => [:lastname, :middlename]

  safe_attributes 'phone', 
                  'address',
                  'skype',
                  'birthday',
                  'job_title',
                  'company',
                  'middlename',
                  'gender',
                  'twitter',
                  'facebook',
                  'linkedin',
                  'department_id',
                  'background',
                  'appearance_date'


  def phones                            
    @phones || self.phone ? self.phone.split( /, */) : []
  end  

  def type
    'User'
  end

  def email
    self.mail
  end

  def project
    nil
  end

  def next_birthday
    return if birthday.blank?
    year = Date.today.year
    mmdd = birthday.strftime('%m%d')
    year += 1 if mmdd < Date.today.strftime('%m%d')
    mmdd = '0301' if mmdd == '0229' && !Date.parse("#{year}0101").leap?
    return Date.parse("#{year}#{mmdd}")
  end

  def self.next_birthdays(limit = 10)
    Person.where("users.birthday IS NOT NULL").sort_by(&:next_birthday).first(limit)
  end

  def age
    return nil if birthday.blank?
    now = Time.now
    age = now.year - birthday.year - (birthday.to_time.change(:year => now.year) > now ? 1 : 0)
  end

  def editable_by?(usr, prj=nil)
    true    
    # usr && (usr.allowed_to?(:edit_people, prj) || (self.author == usr && usr.allowed_to?(:edit_own_invoices, prj))) 
    # usr && usr.logged? && (usr.allowed_to?(:edit_notes, project) || (self.author == usr && usr.allowed_to?(:edit_own_notes, project)))
  end

  def visible?(usr=nil)
    true
  end

  def attachments_visible?(user=User.current)
    true
  end
      
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  unloadable

  Mime::Type.register "text/x-vcard", :vcf

  before_filter :find_person, :only => [:show, :edit, :update, :destroy, :edit_membership, :destroy_membership]
  before_filter :authorize_people, :except => [:avatar, :context_menu]
  before_filter :bulk_find_people, :only => [:context_menu]

  include PeopleHelper
  helper :departments
  helper :context_menus
  helper :custom_fields

  def index
  	@people = find_people
    @groups = Group.all.sort
    @departments = Department.order(:name)
    @next_birthdays = Person.active.next_birthdays
    @new_people = Person.active.where("appearance_date IS NOT NULL").order("appearance_date desc").first(5)

    respond_to do |format|
      format.html {render :partial => 'list_excerpt', :layout => false if request.xhr?}
    end
  end

  def show
    # @person.roles = Role.new(:permissions => [:download_attachments])
    events = Redmine::Activity::Fetcher.new(User.current, :author => @person).events(nil, nil, :limit => 10)
    @events_by_day = events.group_by(&:event_date)
    @person_attachments = @person.attachments.select{|a| a != @person.avatar}
    @memberships = @person.memberships.all(:conditions => Project.visible_condition(User.current))
    respond_to do |format|
      format.html
      format.vcf { send_data(person_to_vcard(@person), :filename => "#{@person.name}.vcf", :type => 'text/x-vcard;', :disposition => 'attachment') }
    end
  end

  def edit
    @auth_sources = AuthSource.find(:all)
    @departments = Department.all.sort
    @membership ||= Member.new
  end

  def new
    @person = Person.new(:language => Setting.default_language, :mail_notification => Setting.default_notification_option, :department_id => params[:department_id])
    @auth_sources = AuthSource.find(:all)
    @departments = Department.all.sort
  end

  def update
    (render_403; return false) unless @person.editable_by?(User.current)
    @person.safe_attributes = params[:person]
    if @person.save
      flash[:notice] = l(:notice_successful_update)
      attach_avatar
      attachments = Attachment.attach_files(@person, params[:attachments])
      render_attachment_warning_if_needed(@person)
      respond_to do |format|
        format.html { redirect_to :action => "show", :id => @person }
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => "edit"}
        format.api  { render_validation_errors(@person) }
      end
    end
  end

  def create
    @person  = Person.new(:language => Setting.default_language, :mail_notification => Setting.default_notification_option)
    @person.safe_attributes = params[:person]
    @person.admin = false
    @person.login = params[:person][:login]
    @person.password, @person.password_confirmation = params[:person][:password], params[:person][:password_confirmation] unless @person.auth_source_id
    @person.type = 'User'
    if @person.save
      @person.pref.attributes = params[:pref]
      @person.pref[:no_self_notified] = (params[:no_self_notified] == '1')
      @person.pref.save
      @person.notified_project_ids = (@person.mail_notification == 'selected' ? params[:notified_project_ids] : [])
      attach_avatar
      Mailer.account_information(@person, params[:person][:password]).deliver if params[:send_information]

      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_successful_create, :id => view_context.link_to(@person.login, person_path(@person)))
          redirect_to(params[:continue] ?
            {:controller => 'people', :action => 'new'} :
            {:controller => 'people', :action => 'show', :id => @person}
          )
        }
        format.api  { render :action => 'show', :status => :created, :location => person_url(@person) }
      end
    else
      @auth_sources = AuthSource.find(:all)
      # Clear password input
      @person.password = @person.password_confirmation = nil

      respond_to do |format|
        format.html { render :action => 'new' }
        format.api  { render_validation_errors(@person) }
      end
    end
  end

  def avatar
    attachment = Attachment.find(params[:id])
    if attachment.readable? && attachment.thumbnailable?
      # images are sent inline
      if (defined?(RedmineContacts::Thumbnail) == 'constant') && Redmine::Thumbnail.convert_available?
        target = File.join(attachment.class.thumbnails_storage_path, "#{attachment.id}_#{attachment.digest}_#{params[:size]}.thumb")
        thumbnail = RedmineContacts::Thumbnail.generate(attachment.diskfile, target, params[:size])
      elsif Redmine::Thumbnail.convert_available?
        thumbnail = attachment.thumbnail(:size => params[:size])
      else
        thumbnail = attachment.diskfile
      end

      if stale?(:etag => attachment.digest)
        send_file thumbnail, :filename => (request.env['HTTP_USER_AGENT'] =~ %r{MSIE} ? ERB::Util.url_encode(attachment.filename) : attachment.filename),
                                        :type => detect_content_type(attachment),
                                        :disposition => 'inline'
      end

    else
      # No thumbnail for the attachment or thumbnail could not be created
      render :nothing => true, :status => 404
    end

  rescue ActiveRecord::RecordNotFound
    render :nothing => true, :status => 404
  end

  def context_menu
    @person = @people.first if (@people.size == 1)
    @can = {:edit =>  @people.collect{|c| User.current.allowed_people_to?(:edit_people, @person)}.inject{|memo,d| memo && d}
            }

    # @back = back_url
    render :layout => false
  end

private
  def authorize_people
    allowed = case params[:action].to_s
      when "create", "new"
        User.current.allowed_people_to?(:add_people, @person)
      when "update", "edit"
        User.current.allowed_people_to?(:edit_people, @person)
      when "delete"
        User.current.allowed_people_to?(:delete_people, @person)
      when "index", "show"
        User.current.allowed_people_to?(:view_people, @person)
      else
        false
      end

    if allowed
      true
    else
      deny_access
    end
  end

  def attach_avatar
    if params[:person_avatar]
      params[:person_avatar][:description] = 'avatar'
      @person.avatar.destroy if @person.avatar
      Attachment.attach_files(@person, {"1" => params[:person_avatar]})
      render_attachment_warning_if_needed(@person)
    end
  end

  def detect_content_type(attachment)
    content_type = attachment.content_type
    if content_type.blank?
      content_type = Redmine::MimeType.of(attachment.filename)
    end
    content_type.to_s
  end

  def find_person
    if params[:id] == 'current'
      require_login || return
      @person = User.current
    else
      @person = Person.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_people(pages=true)
    # scope = scope.scoped(:conditions => ["#{Person.table_name}.status_id = ?", params[:status_id]]) if (!params[:status_id].blank? && params[:status_id] != "o" && params[:status_id] != "d")
    @status = params[:status] || 1
    scope = Person.logged.status(@status)
    scope = scope.seach_by_name(params[:name]) if params[:name].present?
    scope = scope.in_group(params[:group_id]) if params[:group_id].present?
    scope = scope.in_department(params[:department_id]) if params[:department_id].present?
    scope = scope.where(:type => 'User')

    @people_count = scope.count
    @group = Group.find(params[:group_id]) if params[:group_id].present?
    @department = Department.find(params[:department_id]) if params[:department_id].present?
    if pages
      @limit =  per_page_option
      @people_pages = Paginator.new(self, @people_count,  @limit, params[:page])
      @offset = @people_pages.current.offset

      scope = scope.scoped :limit  => @limit, :offset => @offset
      @people = scope

      fake_name = @people.first.name if @people.length > 0 #without this patch paging does not work
    end

    scope
  end

  def bulk_find_people
    @people = Person.find_all_by_id(params[:id] || params[:ids])
    raise ActiveRecord::RecordNotFound if @people.empty?
    if @people.detect {|person| !person.visible?}
      deny_access
      return
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end


end

app/helpers/people_helper.rb
module PeopleHelper

  def birthday_date(person)
    if person.birthday.day == Date.today.day && person.birthday.month == Date.today.month
       "#{l(:label_today).capitalize} (#{person.age + 1})"
    else
      "#{person.birthday.day} #{t('date.month_names')[person.birthday.month]} (#{person.age + 1})"
    end
  end

  def people_principals_check_box_tags(name, principals)
    s = ''
    principals.each do |principal|
      s << "<label>#{ check_box_tag name, principal.id, false, :id => nil } #{principal.is_a?(Group) ? l(:label_group) + ': ' + principal.to_s : principal}</label>\n"
    end
    s.html_safe
  end

  def person_to_vcard(person)
    card = Vcard::Vcard::Maker.make2 do |maker|

      maker.add_name do |name|
        name.prefix = ''
        name.given = person.firstname.to_s
        name.family = person.lastname.to_s
        name.additional = person.middlename.to_s
      end

      maker.add_addr do |addr|
        addr.preferred = true
        addr.street = person.address.to_s.gsub("\r\n"," ").gsub("\n"," ")
      end

      maker.title = person.job_title.to_s
      maker.org = person.company.to_s
      maker.birthday = person.birthday.to_date unless person.birthday.blank?
      maker.add_note(person.background.to_s.gsub("\r\n"," ").gsub("\n", ' '))

      # maker.add_url(person.website.to_s)

      person.phones.each { |phone| maker.add_tel(phone) }

      maker.add_email(person.email)
    end
    avatar = person.avatar
    card = card.encode.sub("END:VCARD", "PHOTO;BASE64:" + "\n " + [File.open(avatar.diskfile).read].pack('m').to_s.gsub(/[ \n]/, '').scan(/.{1,76}/).join("\n ") + "\nEND:VCARD") if avatar && avatar.readable?

    card.to_s

  end

end

app/views/people/_activity.html.erb
<% unless @events_by_day.empty? %>
  <div id="activity">
    <% @events_by_day.keys.sort.reverse.each do |day| %>
    <h4><%= format_activity_day(day) %></h4>
    <dl>
    <% @events_by_day[day].sort {|x,y| y.event_datetime <=> x.event_datetime }.each do |e| -%>
      <dt class="<%= e.event_type %>">
      <span class="time"><%= format_time(e.event_datetime, false) %></span>
      <%= content_tag('span', h(e.project), :class => 'project') %>
      <%= link_to format_activity_title(e.event_title), e.event_url %></dt>
      <dd><span class="description"><%= format_activity_description(e.event_description) %></span></dd>
    <% end -%>
    </dl>
    <% end -%>
  </div>
  <%= link_to l(:label_activity) + " \xc2\xbb", :controller => 'activities',
                :action => 'index', :id => nil, :user_id => @person,
                :from => @events_by_day.keys.first %>
<% end -%>

app/views/people/_attachments.html.erb
<div id="person_files">
  <div class="contextual">     
    <%= link_to l(:button_add), {}, :onclick => "$('#add_attachment_form').show(); $('#add_attachment_link').hide(); return false;", :class => 'icon icon-add', :id => 'add_attachment_link' if User.current.allowed_people_to?(:edit_people, @person) %> 
  </div>
  <%= labelled_form_for :person, @person, 
                               :url => {:action => 'update', :id => @person}, 
                               :html => { :multipart => true, :method => :put, :id => "add_attachment_form", :style => "display:none;" } do |f|  %>
      <fieldset>
        <%= error_messages_for 'person' %>

        <p><%=l(:label_attachment_plural)%><br /><%= render :partial => 'attachments/form', :locals => {:container => @person} %></p>
        <%= submit_tag l(:button_save) -%>   
        <%= link_to l(:button_cancel), {}, :onclick => "$('#add_attachment_form').hide(); $('#add_attachment_link').show(); return false;"  %>  
      </fieldset>
  <% end -%>
  <%= render :partial => 'attachments/links', :locals => {:attachments => @person_attachments, :options  => {:author => true, :deletable => :true}, :thumbnails => Setting.thumbnails_enabled?} %>
</div>

app/views/people/_attributes.html.erb
<div id="attributes">

<div class="contextual">
  <%= link_to 'vCard', person_path(@person, :format => :vcf) %>
</div>

<h3><%= l(:label_people_person) %></h3>

<table class="person attributes vcard">
  <%= call_hook(:view_people_sidebar_attributes_top) %>
	<tr>
		<th class = "first-name"><%= l(:field_name) %>:</th><td class="name fn "><%= @person.firstname %></td>
	</tr>
	<tr>
		<th class = "middle-name"><%= l(:label_people_middlename) %>:</th><td class="name mn "><%= @person.middlename %></td>
	</tr>
	<tr>
		<th class = "last-name"><%= l(:field_lastname) %>:</th><td class="name ln "><%= @person.lastname %></td>
	</tr>
	<% if !@person.job_title.blank? %>
	<tr> <th class = "job_title"><%= l(:label_people_job_title) %>:</th><td class="job_title title"><%= @person.job_title %></td></tr>
	<% end %>
	<tr>
		<th class = "address"><%= l(:label_people_address) %>:</th>
		<td class="address adr"><%= @person.address %>
				<% if !@person.address.blank? %>
					<br>
					<%= link_to l(:label_people_show_on_map), "http://maps.google.com/maps?f=q&q=#{h @person.address.gsub("\r\n"," ").gsub("\n"," ")}+(#{h @person.name})&ie=UTF8&om=1"%>
				<% end %>
		</td>
		</tr>
	<tr class = "tel">
		<th class = "phone"><%= l(:label_people_phone_plural) %>:</th>
		<td class = "phones">
		<% @person.phones.each do |phone| %>
			<span  class="value"><%= h phone %> <br></span>
		 <% end %>
		</td>
	</tr>
	<tr class = "email">
		<th><%= l(:field_mail) %>:</th>
		<td>
			<%= mail_to @person.email  %>
		</td>
	</tr>
 	<% unless @person.skype.blank? %>
	<tr>
	  <th class = "skype"><%= l(:label_people_skype) %>:</th>
	  <td class="skype icon icon-skype"><%= link_to @person.skype, "skype:#{@person.skype}?call" %></td>
	</tr>
	<% end %>
  <% unless @person.twitter.blank? %>
	<tr>
	  <th class = "twitter"><%= l(:label_people_twitter) %>:</th>
	  <td class="twitter icon icon-twitter"><%= link_to @person.twitter, "http://twitter.com/" + @person.twitter %></td>
	</tr>
  <% end %>
  <% unless @person.facebook.blank? %>
	<tr>
	  <th class = "facebook"><%= l(:label_people_facebook) %>:</th>
	  <td class="facebook icon icon-facebook"><%= link_to @person.facebook.gsub(/^.*facebook.com\//, ''), "http://facebook.com/#{@person.facebook}" %></td>
	</tr>
  <% end %>
  <% unless @person.linkedin.blank? %>
	<tr>
	  <th class = "linkedin"><%= l(:label_people_linkedin) %>:</th>
	  <td class="linkedin icon icon-linkedin"><%= link_to @person.name, "http://www.linkedin.com/profile/view?id=#{@person.linkedin}"%></td>
	</tr>
  <% end %>

	<% unless @person.birthday.blank? %>
	<tr> <th class = "birthday"><%= l(:label_people_birthday) %>:</th><td class="birthday bday" title=<%= "#{format_date(@person.birthday)}" %>><%= "#{@person.birthday.day} #{t('date.month_names')[@person.birthday.month]}"%></td> </tr>
	<tr> <th class = "age"><%= l(:label_people_age) %>:</th><td class="ega"><%= @person.age %></td> </tr>
	<% end %>

	<% @person.custom_values.each do |custom_value| %>
		<% if !custom_value.value.blank? %>
		<tr> <th class = "custom_field"><%= custom_value.custom_field.name%>:</th><td> <%=h show_value(custom_value) %></td> </tr>
		<% end %>
	<% end %>

  <tr> <th class = "registered_on"> <%=l(:label_registered_on)%>:</th><td class="registered_on"> <%= format_date(@person.created_on) %></td> </tr>
  <% unless @person.last_login_on.nil? %>
	<tr> <th class = "last_login_on"> <%=l(:field_last_login_on)%>:</th><td class="last_login_on"> <%= format_date(@person.last_login_on) %></td> </tr>
  <% end %>

	<%= call_hook(:view_people_sidebar_attributes_bottom) %>

</table>

</div>

app/views/people/_person_birthday.html.erb
<table class="person_data" id="person_birthday_<%= person_birthday.id %>">
  <tr>
    <td class="avatar"><%= link_to avatar(person_birthday, :size => "32"), person_path(person_birthday), :id => "avatar" %></td>
    <td class="name">
      <h4 class="contacts_header">
        <%= link_to person_birthday.name, person_path(person_birthday) %>
      </h4>
      <p>
          <span class="birthday bday" title=<%= "#{format_date(person_birthday.birthday)}" %>><%= birthday_date(person_birthday) %></span>

      </p>
    </td> 
  </tr>
</table>  

app/views/people/_person_data.html.erb
<table class="person_data" id="person_data_<%= person_data.id %>">
  <tr>
    <td class="avatar"><%= link_to avatar(person_data, :size => "32"), person_path(person_data), :id => "avatar" %></td>
    <td class="name">
      <h4 class="contacts_header">
        <%= link_to person_data.name, person_path(person_data) %>
      </h4>
      <p>
          <span class="job_title"><%= person_data.job_title %></span>

      </p>
    </td> 
  </tr>
</table>  

app/views/people/_projects.html.erb
<% unless @memberships.empty? %>
<ul>
<% for membership in @memberships %>
  <li><%= link_to_project(membership.project) %>
    (<%=h membership.roles.sort.collect(&:to_s).join(', ') %>, <%= format_date(membership.created_on) %>)</li>
<% end %>
</ul>
<% end %>
</div>

app/views/people/edit.html.erb
<div class="contextual">  
    <%= link_to(l(:button_people_edit_profile), edit_user_path(@person), :class => 'icon icon-edit') if User.current.admin? %>
</div>    

<h2><%= l(:label_people_edit_person) %></h2>

<%= labelled_form_for :person, @person, 
                             :url => {:action => 'update', :id => @person}, 
                             :html => { :multipart => true, :method => :put, :id => "person_form" } do |f|  %>
  <%= error_messages_for 'person' %>

  <%= render :partial => 'form', :locals => {:f => f} %>    
  <%= submit_tag l(:button_save) -%>    
<% end -%>

<% content_for :sidebar do %>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :people, :plugin => 'redmine_people'  %>
  <%= stylesheet_link_tag :people, :plugin => 'redmine_people' %>
  <%= robot_exclusion_tag %>
<% end %>

app/views/people/index.html.erb
<div class="contextual">
  <%= link_to l(:label_user_new), {:controller => 'people', :action => 'new', :project_id => @project, :department_id => @department}, :class => 'icon icon-add' if User.current.allowed_people_to?(:add_people, @person) %>
</div>



<div class="filters">   
	<%= form_tag({:contoller => "people", :action => "index"}, :method => :get,  :id => "query_form") do %> 
		<%= hidden_field_tag('project_id', @project.to_param) if @project %>   
		<% no_filters = true %>	
    
    <script type="text/javascript">
       jQuery(function($) {
          // when the #search field changes
          $("#name").observe_field(2, function() {
            var form = $("#query_form"); // grab the form wrapping the search bar.
            var url = form.attr("action");
            var formData = form.serialize();
            $.get(url, formData, function(data) { // perform an AJAX get, the trailing function is what happens on successful get.
                $("#people_list").html(data); // replace the "results" div with the result of action taken
            });
          });
        });
    </script>

    <h2 class="contacts_header">
        <span id='scope_header' class="scope_title"> 
        <%= @group ? @group.name : (@department ? @department.name : l(:label_people))  %>
        </span>

        <span class="live_search">  
            <%= text_field_tag(:name, params[:name], :autocomplete => "off", :class => "live_search_field", :placeholder => l(:label_people_search) ) %>    

        </span>

    </h2>		
	
<!-- 	<fieldset id="filters" class="collapsible <%= 'collapsed' if no_filters %>">
		<legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
		<div style="<%= 'display: none;' if no_filters %>">  
			<p>  

			</p>    

		</div>
	</fieldset> 

	<p class="buttons hide-when-print">
		<%= link_to l(:button_apply), "#", :onclick=>"$('#query_form').submit()", :class => 'icon icon-checked' %>
    	<%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
	</p>   
 -->                                                                   
	<% end %>  

</div>

<div id="people_list">  
<% if @people.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  	<%= render :partial => 'list_excerpt' %>
<% end %>
</div>  

<!-- <PRO> -->
<% other_formats_links do |f| %>
    <%= f.link_to 'CSV', :url => params %>    
<% end if false%>
<!-- </PRO> -->
                     
<% html_title l(:label_people) %>                                                                     

<%= context_menu url_for( {:controller => "people", :action => "context_menu"} )%>  

<% content_for :sidebar do %>
	<div id="people_groups">
		<h3><%= l(:label_people_group_plular) %></h3>
		<ul>
			<li>
				<%= link_to l(:label_people_all), {} %>
			</li>
		<% @groups.each do |group| %>
			<li>
				<%= link_to group.name, {:group_id => group.id}, :class => "#{'selected' if @group && group == @group}"  %>
			</li>	
		<% end %>
		</ul>
	</div>

  <% unless @departments.blank? %>
  <div id="people_departments">
    <div class="contextual">
      <%= link_to l(:button_edit), departments_path if User.current.allowed_people_to?(:edit_departments) %>
    </div>    
    <h3><%= l(:label_department_plural) %></h3>
    <%= department_tree_links(@departments) %>
  </div>  
  <% end %>

  <div id="next_birthdays">
    <h3><%= l(:label_people_next_birthdays) %></h3>
    <%= render :partial => 'person_birthday', :collection => @next_birthdays %>
  </div>

  <div id="new_people">
    <h3><%= l(:label_people_new_people) %></h3>
    <%= render :partial => 'person_data', :collection => @new_people %>
  </div>

<% end %>

<% content_for :header_tags do %>
    <%= javascript_include_tag :people, :plugin => 'redmine_people'  %>
	<%= stylesheet_link_tag :people, :plugin => 'redmine_people' %> 
	<meta name = "format-detection" content = "telephone=no">
<% end %>

app/views/people/show.html.erb
<%= error_messages_for 'person' %>

<% html_title "#{l(:label_people_person)} ##{@person.id}: #{@person.name}" %>

<div class="contextual">
  <%= link_to l(:label_profile), user_path(@person), :class => 'icon icon-user' %>
  <%= link_to l(:button_edit), {:controller => 'people', :action => 'edit', :id => @person}, :class => 'icon icon-edit' if User.current.allowed_people_to?(:edit_people, @person) %>
  <%= link_to l(:button_delete), {:controller => 'users', :action => 'destroy', :project_id => @project, :id => @person}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' if User.current.allowed_people_to?(:delete_people, @person) %>
</div>

<h2><%= l(:label_people_person) %> #<%= @person.id %></h2>
<div class="person details">
  <table class="subject_header">
    <tr>
      <td class="avatar"><%= link_to avatar(@person, :size => "64", :full_size => true), @person.avatar %></td>
      <td class="name" style="vertical-align: top;">
        <h1><%= h @person.name %></h1>
        <p>
        <%= h @person.job_title %>
        <% if @person.department %>
          <%= " #{l(:label_people_at_department)} " %>
          <%= link_to @person.department.name, {:controller => 'departments', :action => 'show', :id => @person.department_id } %>
        <% end %>
        </p>
      </td>
      <td class="subject_info">
        <ul>
          <% if @person.phones.any? %>
            <li class="phone icon icon-phone"><%=  @person.phones.first %></li>
          <% end %>
          <li class="email icon icon-email"><%= mail_to @person.email %></li>
        </ul>
      </td>
    </tr>
  </table>

  <%= call_hook(:view_people_show_details_bottom, :person => @person) %>
</div>



<% person_tabs = [{:name => 'activity', :partial => 'activity', :label => :label_activity},
        {:name => 'files', :partial => 'attachments', :label => :label_attachment_plural},
        {:name => 'projects', :partial => 'projects', :label => :label_project_plural}
        ]   %>

<%= render_tabs person_tabs %>


<% content_for :sidebar do %>
  <%= render :partial => 'attributes' %>
  <%= call_hook(:view_people_sidebar_after_attributes, :person => @person) %>
  <% if !@person.background.blank? %>
    <h3><%= l(:label_people_background) %></h3>
    <div class="wiki"><%= textilizable(@person, :background) %></div>
  <% end %>
<% end %>



<% content_for :header_tags do %>
  <%= javascript_include_tag :people, :plugin => 'redmine_people'  %>
  <%= stylesheet_link_tag :people, :plugin => 'redmine_people' %>
<% end %>